version: "3"

networks:
  confluent:

services:
  loki:
    image: grafana/loki:latest
    command: -config.file=/etc/loki/loki-config.yaml
    volumes:
      - ./loki:/etc/loki
    ports:
      - "3100:3100"
    networks:
      - confluent

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - '9090:9090'
    restart: unless-stopped
    volumes:
      - ./prometheus/prometheus-config.yaml:/etc/prometheus/prometheus-config.yaml
      - ./prometheus/rules.yaml:/etc/prometheus/rules.yaml
    command:
      - '--web.enable-lifecycle'
      - '--config.file=/etc/prometheus/prometheus-config.yaml'
    networks:
      - confluent

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - ./grafana:/etc/grafana/provisioning
      - ./grafana/datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
    networks:
      - confluent

  alertmanager:
    image: prom/alertmanager:latest
    restart: unless-stopped
    ports:
      - "9093:9093"
    volumes:
      - "./alertmanager:/config"
      - alertmanager-data:/data
    command: --config.file=/config/alertmanager-config.yaml --log.level=debug
    networks:
      - confluent


volumes:

  alertmanager-data:




